[package]
name = "martensite-blessed"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Curated tier-1 ecosystem extensions for the Martensite GUI framework"
readme = "README.md"

[dependencies]
martensite = { workspace = true }
martensite-core = { workspace = true }
martensite-render = { workspace = true }
martensite-text = { workspace = true }

[dev-dependencies]
martensite-plugin = { workspace = true }
martensite-test = { workspace = true }

[lints]
workspace = true
