[package]
name = "martensite-plugin"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Wasmtime sandboxed plugin runtime for Martensite."
readme = "README.md"

[dependencies]
wasmtime = "36.0.14"
wasmtime-wasi = "36.0.14"
martensite-core = { workspace = true }
martensite-render = { workspace = true }
martensite-reactive = { workspace = true }

[dev-dependencies]
wat = "1.219"

[lints]
workspace = true
