[package]
name = "cargo-martensite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Developer CLI toolchain for sub-second hot-reloading and asset compilation."
readme = "README.md"
publish = false

[dependencies]
wgpu = { workspace = true }
pollster = { workspace = true }
fontdb = { workspace = true, features = ["std", "fontconfig"] }
martensite-design-lint = { workspace = true }
martensite-devtools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ed25519-dalek = { version = "2", default-features = false, features = ["fast", "std", "rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
sha2 = "0.10"
hex = "0.4"
semver = "1.0"


[dev-dependencies]
tempfile = "3.27"
martensite-host = { workspace = true }
toml = "0.9"

[lib]
name = "cargo_martensite"
path = "src/lib.rs"

[lints]
workspace = true
