[package]
name = "cargo-martensite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Developer CLI toolchain for sub-second hot-reloading and asset compilation."
readme = "README.md"
publish = false

[dependencies]

[dev-dependencies]
tempfile = "3.27"

[lib]
name = "cargo_martensite"
path = "src/lib.rs"

[lints]
workspace = true
