[package]
name = "martensite-l10n"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Natural language grammatical localization and BiDi mirroring via Project Fluent."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
martensite-reactive = { workspace = true }
fluent-bundle = { workspace = true }
unic-langid = { workspace = true }
fluent-langneg = { workspace = true }

[lints]
workspace = true
