[package]
name = "martensite-assets"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Virtual file system (VFS), AOT naga shader validation, and dynamic texture streaming."
publish = false
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
[lints]
workspace = true
