[package]
name = "martensite-dnd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Unified internal scenegraph and cross-OS native drag-and-drop subsystem."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
glam = { workspace = true }
bitflags = { workspace = true }
winit = { workspace = true }

[lints]
workspace = true
