[package]
name = "martensite-render"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Hardware-agnostic PaintList command stream and TinySkia CPU fallback backend."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
tiny-skia = { workspace = true }
softbuffer = { workspace = true }
kurbo = { workspace = true }
peniko = { workspace = true }
[lints]
workspace = true
