[package]
name = "martensite-accesskit-winit"
version.workspace = true
authors.workspace = true
license = "Apache-2.0"
description = "Vendored and patched AccessKit winit adapter for winit 0.31.0-beta.3"
categories.workspace = true
keywords = ["gui", "ui", "accessibility", "winit"]
repository.workspace = true
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "accesskit_winit"
path = "src/lib.rs"

[features]
default = ["accesskit_unix", "async-io"]
async-io = ["accesskit_unix/async-io"]
tokio = ["accesskit_unix/tokio"]

[dependencies]
accesskit = { workspace = true }
winit = { workspace = true }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = ["std"] }

[target.'cfg(target_os = "windows")'.dependencies]
accesskit_windows = { version = "0.35.0" }

[target.'cfg(target_os = "macos")'.dependencies]
accesskit_macos = { version = "0.27.0" }

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
accesskit_unix = { version = "0.23.0", optional = true, default-features = false }

[target.'cfg(target_os = "android")'.dependencies]
accesskit_android = { version = "0.8.0", optional = true, features = ["embedded-dex"] }

[target.'cfg(target_os = "ios")'.dependencies]
accesskit_ios = { version = "0.2.0" }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dev-dependencies.softbuffer]
version = "0.4.8"
default-features = false
features = ["x11", "x11-dlopen", "wayland", "wayland-dlopen"]

[target.'cfg(target_os = "ios")'.dev-dependencies.softbuffer]
version = "0.4.8"
default-features = false
