[package]
name = "martensite-window"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Winit multi-window management, fractional DPI scaling, and decoupled VSync."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
slotmap = { workspace = true }

[features]
docs-rs = ["winit/x11"]

[package.metadata.docs.rs]
features = ["docs-rs"]
[lints]
workspace = true
