[package]
name = "martensite-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Compute-centric 2D GPU rasterization and self-healing WGPU device pipeline."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
martensite-render = { workspace = true }
wgpu = { workspace = true }
vello = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
[lints]
workspace = true
