[package]
name = "martensite-layout"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "W3C CSS Flexbox, Grid, and Block layout bridge via Taffy for Martensite."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
taffy = { workspace = true }
glam = { workspace = true }
[lints]
workspace = true
