[package]
name = "industrial_dashboard"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Industrial dashboard example application for Martensite."
readme = "README.md"
publish = false

[dependencies]
martensite = { workspace = true }

[lints]
workspace = true
