[package]
name = "martensite-access"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
description = "Native operating system accessibility integration via AccessKit."
readme = "README.md"

[dependencies]
martensite-core = { workspace = true }
accesskit = { workspace = true }
accesskit_winit = { workspace = true }
winit = { workspace = true }
unicode-segmentation = "1.12"
unicode-bidi = { workspace = true }

[dev-dependencies]
glam = { workspace = true }
uuid = { version = "1", features = ["v4"] }

[features]
docs-rs = ["winit/x11"]

[package.metadata.docs.rs]
features = ["docs-rs"]
[lints]
workspace = true
